### ISSUE TITLE
NoMethodError: undefined method `each_pair' for []:Array

### ISSUE THREAD

**Issue by pupeno** [SchemaPlus/schema_validations#19]
When I add schema_validations to my Rails project (Rails 4.2.1, Ruby 2.2.1) I get the following error:

```
$ rake --trace db:migrate
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Invoke db:load_config (first_time)
** Execute db:load_config
** Execute db:migrate
== 20150411095841 DeviseCreateUsers: migrating ================================
-- create_table(:users)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `each_pair' for []:Array/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus-1.8.7/lib/schema_plus/active_record/connection_adapters/schema_statements.rb:39:in `create_table_with_schema_plus'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/pupeno/Projects/buzz/db/migrate/20150411095841_devise_create_users.rb:5:in `change'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
NoMethodError: undefined method `each_pair' for []:Array
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:216:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus-1.8.7/lib/schema_plus/active_record/connection_adapters/schema_statements.rb:39:in `create_table_with_schema_plus'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/pupeno/Projects/buzz/db/migrate/20150411095841_devise_create_users.rb:5:in `change'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:606:in `exec_migration'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/benchmark.rb:288:in `measure'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/pupeno/.rvm/rubies/ruby-2.2.1/bin/rake:33:in `<main>'
Tasks: TOP => db:migrate
```

**Comment by ronen** [comment]
schema_validations depends on schema_plus, and the current release of schema_plus, 1.8.7, doesn't support rails 4.2.1.   but the prerelease, schema_plus 2.0.0.pre12 should work fine.  so if you add

    gem "schema_plus", "2.0.0.pre12"

to your project it should be OK.

**Comment by pupeno** [comment]
Awesome. Thanks.
