### ISSUE TITLE
Presence of schema_validations makes active_admin migration fail

### ISSUE THREAD

**Issue by pupeno** [SchemaPlus/schema_validations#20]
When running the migrations required for active_admin, if schema_validation (2.0.0.pre12) is present, I get an exception. I didn't investigate it, I'm just reporting it:

```
== 20150411111402 CreateActiveAdminComments: migrating ========================
-- create_table(:active_admin_comments)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::UndefinedTable: ERROR:  relation "resources" does not exist
: CREATE TABLE "active_admin_comments" ("id" serial primary key, "namespace" character varying , "body" text , "resource_id" character varying NOT NULL, "resource_type" character varying NOT NULL, "author_id" integer , "author_type" character varying , "created_at" timestamp , "updated_at" timestamp , CONSTRAINT fk_active_admin_comments_resource_id FOREIGN KEY ("resource_id") REFERENCES "resources" ("id"))/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:27:in `block in create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:74:in `block in _modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus-2.0.0.pre12/lib/schema_plus/foreign_keys/middleware/migration.rb:14:in `around'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:73:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:83:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_monkey-2.1.0/lib/schema_monkey/stack.rb:34:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:26:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/Users/pupeno/Projects/buzz/db/migrate/20150411111402_create_active_admin_comments.rb:5:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pupeno/Projects/buzz/lib/tasks/fake_data.rake:8:in `block (2 levels) in <top (required)>'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "resources" does not exist
: CREATE TABLE "active_admin_comments" ("id" serial primary key, "namespace" character varying , "body" text , "resource_id" character varying NOT NULL, "resource_type" character varying NOT NULL, "author_id" integer , "author_type" character varying , "created_at" timestamp , "updated_at" timestamp , CONSTRAINT fk_active_admin_comments_resource_id FOREIGN KEY ("resource_id") REFERENCES "resources" ("id"))
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:27:in `block in create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:74:in `block in _modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus-2.0.0.pre12/lib/schema_plus/foreign_keys/middleware/migration.rb:14:in `around'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:73:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:83:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_monkey-2.1.0/lib/schema_monkey/stack.rb:34:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:26:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/Users/pupeno/Projects/buzz/db/migrate/20150411111402_create_active_admin_comments.rb:5:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pupeno/Projects/buzz/lib/tasks/fake_data.rake:8:in `block (2 levels) in <top (required)>'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
PG::UndefinedTable: ERROR:  relation "resources" does not exist
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `async_exec'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:155:in `block in execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:473:in `block in log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract_adapter.rb:467:in `log'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:154:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:208:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:27:in `block in create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:55:in `call_implementation'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:85:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:74:in `block in _modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus-2.0.0.pre12/lib/schema_plus/foreign_keys/middleware/migration.rb:14:in `around'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:73:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:83:in `_modware_continue'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:77:in `_modware_call'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:44:in `execute'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/modware-0.1.2/lib/modware/stack.rb:20:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_monkey-2.1.0/lib/schema_monkey/stack.rb:34:in `start'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/schema_plus_core-0.3.0/lib/schema_plus/core/active_record/connection_adapters/abstract_adapter.rb:26:in `create_table'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:662:in `block in method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `block in say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:632:in `say_with_time'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:652:in `method_missing'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:417:in `method_missing'
/Users/pupeno/Projects/buzz/db/migrate/20150411111402_create_active_admin_comments.rb:5:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:569:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:609:in `exec_migration'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:590:in `block (2 levels) in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:589:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:292:in `with_connection'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:588:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:765:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:995:in `block in execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `block in ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/transactions.rb:220:in `transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:1041:in `ddl_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:994:in `execute_migration_in_transaction'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:956:in `block in migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `each'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:952:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:820:in `up'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/migration.rb:798:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/tasks/database_tasks.rb:137:in `migrate'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activerecord-4.2.1/lib/active_record/railties/databases.rake:44:in `block (2 levels) in <top (required)>'
/Users/pupeno/Projects/buzz/lib/tasks/fake_data.rake:8:in `block (2 levels) in <top (required)>'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/pupeno/.rvm/gems/ruby-2.2.1@buzz/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
-e:1:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

These are the active admin migrations:

```ruby
class DeviseCreateAdminUsers < ActiveRecord::Migration
  def change
    create_table(:admin_users) do |t|
      ## Database authenticatable
      t.string :email, null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

      ## Recoverable
      t.string :reset_password_token
      t.datetime :reset_password_sent_at

      ## Rememberable
      t.datetime :remember_created_at

      ## Trackable
      t.integer :sign_in_count, default: 0, null: false
      t.datetime :current_sign_in_at
      t.datetime :last_sign_in_at
      t.inet :current_sign_in_ip
      t.inet :last_sign_in_ip

      ## Confirmable
      # t.string   :confirmation_token
      # t.datetime :confirmed_at
      # t.datetime :confirmation_sent_at
      # t.string   :unconfirmed_email # Only if using reconfirmable

      ## Lockable
      t.integer :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
      t.string :unlock_token # Only if unlock strategy is :email or :both
      t.datetime :locked_at

      t.timestamps
    end

    add_index :admin_users, :email, unique: true
    add_index :admin_users, :reset_password_token, unique: true
    # add_index :admin_users, :confirmation_token,   unique: true
    add_index :admin_users, :unlock_token, unique: true
  end
end
```

and

```ruby
class CreateActiveAdminComments < ActiveRecord::Migration
  def self.up
    create_table :active_admin_comments do |t|
      t.string :namespace
      t.text :body
      t.string :resource_id, null: false
      t.string :resource_type, null: false
      t.references :author, polymorphic: true
      t.timestamps
    end
    add_index :active_admin_comments, [:namespace]
    add_index :active_admin_comments, [:author_type, :author_id]
    add_index :active_admin_comments, [:resource_type, :resource_id]
  end

  def self.down
    drop_table :active_admin_comments
  end
end
```

**Comment by ronen** [comment]
@pupeno schema_plus currently by default has automatic behavior to assume that any column named "something_id" is intended to be a reference to table "somethings" and so attempts to create a foreign key constraint for it.

You can disable that in a rails initialization file by doing:

````ruby
SchemaPlus.setup do |config|
       config.foreign_keys.auto_create = false
end
````

(You might want to disable it while running the active_admin migration, then re-enabled it again afterwards.)

**Comment by JasonBarnabe** [comment]
I got bit by this too. It's annoying to have my migrations break by installing this gem.

I'm unsure what in schema_plus this is using, but it looks like some of the functionality has been extracted to https://github.com/SchemaPlus/schema_plus_core - could this be used instead?

**Comment by ronen** [comment]
@JasonBarnabe 
>  It's annoying to have my migrations break by installing this gem.

I agree

> I'm unsure what in schema_plus this is using, but it looks like some of the functionality has been extracted to https://github.com/SchemaPlus/schema_plus_core - could this be used instead?

Yes, you're right, schema_plus has now been split up for version 2.0, in order to avoid this sort of over-inclusion of unwanted features.  Actually schema_plus is still in the process of being split up, there's still more to do there -- but https://github.com/SchemaPlus/schema_plus_columns has already been extracted and is all that's needed here.

I've released schema_validations 1.2.0 which depends only on schema_plus_columns and doesn't pull in the automatic foreign key creation behavior.   Note thought that schema_plus_columns only supports ActiveRecord 4.2, and I've further limited this release to ~> ActiveRecord 4.2.1, to avoid potential conflicts with schema_plus 1.8 which supports ActiveRecord <= 4.2.0

**Comment by JasonBarnabe** [comment]
Great, thanks!

**Comment by AlanLattimore** [comment]
For anyone else who stumbles this way, adding `foreign_key: false` to `t.string :resource_id` solved my problem.
```
class CreateActiveAdminComments < ActiveRecord::Migration
  def self.up
    create_table :active_admin_comments do |t|
      t.string :namespace
      t.text   :body
      t.string :resource_id,   null: false, foreign_key: false
      t.string :resource_type, null: false
      t.references :author, polymorphic: true
      t.timestamps
    end
    add_index :active_admin_comments, [:namespace]
    add_index :active_admin_comments, [:author_type, :author_id]
    add_index :active_admin_comments, [:resource_type, :resource_id]
  end

  def self.down
    drop_table :active_admin_comments
  end
end
```
